Added Aim and First Shot Variance.
Joe91/fun-bots pull request #40
Opened 2021-02-23 15:30 UTC by SmartShots

Adds a random variance of between 0 and 0.2
to both bot aim and first shot delay.

2021-02-23 19:28 UTC, Joe91 requested changes
We can discuss about a better solution...
I would also suggest do add the Randomness as Config-Value, as already discussed...

2021-02-23 19:28 UTC, Joe91 commented on ext/Server/Bot.lua
> +	FirstShotRandomness = math.random (0, 2) / 10;
Lets use MathUtils:GetRandom(from, to) here
This looks nicer and returns directly in float
```suggestion
	FirstShotRandomness = MathUtils:GetRandom(0, 0.2);
```

2021-02-23 19:28 UTC, Joe91 commented on ext/Server/Bot.lua
> +	Config.botFirstShotDelay = Config.botFirstShotDelay + FirstShotRandomness;
Don't write on the Config.vars, as they get used by the UI!! Use something like that instead:
`self._shotTimer = -MathUtils:GetRandom(Config.botFirstShotDelay, Config.botFirstShotDelay + 0.2);`

2021-02-23 19:28 UTC, Joe91 commented on ext/Shared/WeaponModification.lua
> +	botAimRandomness = math.random (0, 2) / 10;
I think we should wait with the aim-modification until its possible to do this for each weapon individually. I will have a look at it...

2021-02-24 09:32 UTC, SmartShots commented
I agree, it's a good idea but would be much better if we can find a way to get it to work per BOT or at least to update the weapon on BOT spawn.

2021-02-24 09:32 UTC, closed without merging